services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DATABASE
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - db:/var/lib/postgres

  backend-app:
    depends_on:
      - postgresdb
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_PORT:$NODE_PORT
    environment:
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DATABASE=$POSTGRES_DATABASE
      - POSTGRES_PORT=$POSTGRES_PORT

volumes:
  db:
